// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGbz2dRqnnEwvdrhGJfA8rYvargYLD0k',
    appId: '1:538629235356:web:d8529bf53131794abe0359',
    messagingSenderId: '538629235356',
    projectId: 'anatcha-foodapp',
    authDomain: 'anatcha-foodapp.firebaseapp.com',
    storageBucket: 'anatcha-foodapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgD929sf2u6EIQaCAWYQMSJVFc8iUkhDk',
    appId: '1:519800441504:android:c0d67541d35ce6d96097c5',
    messagingSenderId: '519800441504',
    projectId: 'flag-pic-fe78f',
    storageBucket: 'flag-pic-fe78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD39-QmXHdhS-JPP1VNWKQxjKlLuy7mQII',
    appId: '1:538629235356:ios:bf9ada54a8d9ab6cbe0359',
    messagingSenderId: '538629235356',
    projectId: 'anatcha-foodapp',
    storageBucket: 'anatcha-foodapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD39-QmXHdhS-JPP1VNWKQxjKlLuy7mQII',
    appId: '1:538629235356:ios:bf9ada54a8d9ab6cbe0359',
    messagingSenderId: '538629235356',
    projectId: 'anatcha-foodapp',
    storageBucket: 'anatcha-foodapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDGbz2dRqnnEwvdrhGJfA8rYvargYLD0k',
    appId: '1:538629235356:web:dd4b145042c26500be0359',
    messagingSenderId: '538629235356',
    projectId: 'anatcha-foodapp',
    authDomain: 'anatcha-foodapp.firebaseapp.com',
    storageBucket: 'anatcha-foodapp.firebasestorage.app',
  );
}